// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// space_shooting
List space_shooting(NumericVector Y_data, NumericVector sigma_sr, int NN, int PP, int QQ, double L1, int n_iter, Rcpp::Nullable<Rcpp::NumericVector> beta_init);
RcppExport SEXP _matSPACE_space_shooting(SEXP Y_dataSEXP, SEXP sigma_srSEXP, SEXP NNSEXP, SEXP PPSEXP, SEXP QQSEXP, SEXP L1SEXP, SEXP n_iterSEXP, SEXP beta_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y_data(Y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_sr(sigma_srSEXP);
    Rcpp::traits::input_parameter< int >::type NN(NNSEXP);
    Rcpp::traits::input_parameter< int >::type PP(PPSEXP);
    Rcpp::traits::input_parameter< int >::type QQ(QQSEXP);
    Rcpp::traits::input_parameter< double >::type L1(L1SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_init(beta_initSEXP);
    rcpp_result_gen = Rcpp::wrap(space_shooting(Y_data, sigma_sr, NN, PP, QQ, L1, n_iter, beta_init));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_matSPACE_space_shooting", (DL_FUNC) &_matSPACE_space_shooting, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_matSPACE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
